"""Seed geographic boundaries and multi-box country borders for scraping."""

from sqlmodel import Session, select

from app.db.models import GeoBoundary, GeoBoundaryBox
from app.logger import get_logger

logger = get_logger(__name__)

# Geographic boundaries for countries, states, and cities
GEO_BOUNDARIES = [
    # ── Countries ────────────────────────────────────────────────────────────────
    {
        "name": "UAE",
        "boundary_type": "country",
        "country": None,
        "state": None,
        "lat_min": 22.5,
        "lat_max": 26.0,
        "lng_min": 51.5,
        "lng_max": 56.5,
        "radius_km": 400.0,
    },
    {
        "name": "India",
        "boundary_type": "country",
        "country": None,
        "state": None,
        "lat_min": 8.0,
        "lat_max": 35.5,
        "lng_min": 68.0,
        "lng_max": 97.5,
        "radius_km": 1800.0,
    },
    {
        "name": "USA",
        "boundary_type": "country",
        "country": None,
        "state": None,
        "lat_min": 24.5,
        "lat_max": 49.0,
        "lng_min": -125.0,
        "lng_max": -66.0,
        "radius_km": 2500.0,
    },
    {
        "name": "Pakistan",
        "boundary_type": "country",
        "country": None,
        "state": None,
        "lat_min": 23.5,
        "lat_max": 37.1,
        "lng_min": 60.9,
        "lng_max": 77.8,
        "radius_km": 1100.0,
    },
    # ── USA States ───────────────────────────────────────────────────────────────
    {
        "name": "California",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 32.5,
        "lat_max": 42.0,
        "lng_min": -124.5,
        "lng_max": -114.0,
        "radius_km": 600.0,
    },
    {
        "name": "Texas",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 25.8,
        "lat_max": 36.5,
        "lng_min": -106.6,
        "lng_max": -93.5,
        "radius_km": 650.0,
    },
    {
        "name": "New York",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 40.5,
        "lat_max": 45.0,
        "lng_min": -79.8,
        "lng_max": -71.9,
        "radius_km": 350.0,
    },
    {
        "name": "Florida",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 24.5,
        "lat_max": 31.0,
        "lng_min": -87.6,
        "lng_max": -80.0,
        "radius_km": 450.0,
    },
    {
        "name": "Illinois",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 36.9,
        "lat_max": 42.5,
        "lng_min": -91.5,
        "lng_max": -87.0,
        "radius_km": 350.0,
    },
    {
        "name": "Pennsylvania",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 39.7,
        "lat_max": 42.3,
        "lng_min": -80.5,
        "lng_max": -74.7,
        "radius_km": 300.0,
    },
    {
        "name": "Ohio",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 38.4,
        "lat_max": 42.0,
        "lng_min": -84.8,
        "lng_max": -80.5,
        "radius_km": 280.0,
    },
    {
        "name": "Georgia",
        "boundary_type": "state",
        "country": "USA",
        "state": None,
        "lat_min": 30.4,
        "lat_max": 35.0,
        "lng_min": -85.6,
        "lng_max": -80.8,
        "radius_km": 340.0,
    },
    # ── India States ─────────────────────────────────────────────────────────────
    {
        "name": "Maharashtra",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 15.6,
        "lat_max": 22.1,
        "lng_min": 72.6,
        "lng_max": 80.9,
        "radius_km": 550.0,
    },
    {
        "name": "Uttar Pradesh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 23.8,
        "lat_max": 30.4,
        "lng_min": 77.1,
        "lng_max": 84.6,
        "radius_km": 500.0,
    },
    {
        "name": "West Bengal",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 21.5,
        "lat_max": 27.2,
        "lng_min": 85.8,
        "lng_max": 89.9,
        "radius_km": 400.0,
    },
    {
        "name": "Tamil Nadu",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 8.1,
        "lat_max": 13.6,
        "lng_min": 76.2,
        "lng_max": 80.4,
        "radius_km": 420.0,
    },
    {
        "name": "Rajasthan",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 23.0,
        "lat_max": 30.2,
        "lng_min": 69.5,
        "lng_max": 78.3,
        "radius_km": 560.0,
    },
    {
        "name": "Karnataka",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 11.6,
        "lat_max": 18.5,
        "lng_min": 74.0,
        "lng_max": 78.6,
        "radius_km": 440.0,
    },
    {
        "name": "Gujarat",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 20.1,
        "lat_max": 24.7,
        "lng_min": 68.2,
        "lng_max": 74.5,
        "radius_km": 430.0,
    },
    {
        "name": "Andhra Pradesh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 12.6,
        "lat_max": 19.1,
        "lng_min": 77.0,
        "lng_max": 84.6,
        "radius_km": 490.0,
    },
    {
        "name": "Madhya Pradesh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 21.1,
        "lat_max": 26.9,
        "lng_min": 74.0,
        "lng_max": 82.8,
        "radius_km": 560.0,
    },
    {
        "name": "Bihar",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 24.3,
        "lat_max": 27.5,
        "lng_min": 83.3,
        "lng_max": 88.3,
        "radius_km": 380.0,
    },
    {
        "name": "Telangana",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 15.8,
        "lat_max": 19.9,
        "lng_min": 77.2,
        "lng_max": 81.8,
        "radius_km": 380.0,
    },
    {
        "name": "Odisha",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 17.8,
        "lat_max": 22.6,
        "lng_min": 81.4,
        "lng_max": 87.5,
        "radius_km": 420.0,
    },
    {
        "name": "Kerala",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 8.2,
        "lat_max": 12.8,
        "lng_min": 74.9,
        "lng_max": 77.4,
        "radius_km": 310.0,
    },
    {
        "name": "Haryana",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 27.7,
        "lat_max": 30.9,
        "lng_min": 74.5,
        "lng_max": 77.6,
        "radius_km": 280.0,
    },
    {
        "name": "Punjab",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 29.5,
        "lat_max": 32.5,
        "lng_min": 73.9,
        "lng_max": 76.9,
        "radius_km": 260.0,
    },
    {
        "name": "Assam",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 24.1,
        "lat_max": 28.2,
        "lng_min": 89.7,
        "lng_max": 96.0,
        "radius_km": 400.0,
    },
    {
        "name": "Jharkhand",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 21.9,
        "lat_max": 25.3,
        "lng_min": 83.3,
        "lng_max": 87.9,
        "radius_km": 320.0,
    },
    {
        "name": "Chhattisgarh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 17.8,
        "lat_max": 24.1,
        "lng_min": 80.3,
        "lng_max": 84.4,
        "radius_km": 420.0,
    },
    {
        "name": "Uttarakhand",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 28.7,
        "lat_max": 31.5,
        "lng_min": 77.6,
        "lng_max": 81.0,
        "radius_km": 270.0,
    },
    {
        "name": "Himachal Pradesh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 30.4,
        "lat_max": 33.2,
        "lng_min": 75.6,
        "lng_max": 79.0,
        "radius_km": 260.0,
    },
    {
        "name": "Jammu and Kashmir",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 32.3,
        "lat_max": 36.9,
        "lng_min": 73.8,
        "lng_max": 80.4,
        "radius_km": 420.0,
    },
    {
        "name": "Goa",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 14.9,
        "lat_max": 15.8,
        "lng_min": 73.7,
        "lng_max": 74.3,
        "radius_km": 60.0,
    },
    {
        "name": "Tripura",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 22.9,
        "lat_max": 24.5,
        "lng_min": 91.1,
        "lng_max": 92.3,
        "radius_km": 120.0,
    },
    {
        "name": "Manipur",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 23.8,
        "lat_max": 25.7,
        "lng_min": 93.0,
        "lng_max": 94.8,
        "radius_km": 140.0,
    },
    {
        "name": "Meghalaya",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 25.0,
        "lat_max": 26.1,
        "lng_min": 89.8,
        "lng_max": 92.8,
        "radius_km": 180.0,
    },
    {
        "name": "Nagaland",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 25.2,
        "lat_max": 27.0,
        "lng_min": 93.3,
        "lng_max": 95.3,
        "radius_km": 150.0,
    },
    {
        "name": "Arunachal Pradesh",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 26.6,
        "lat_max": 29.5,
        "lng_min": 91.6,
        "lng_max": 97.4,
        "radius_km": 420.0,
    },
    {
        "name": "Mizoram",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 21.9,
        "lat_max": 24.5,
        "lng_min": 92.3,
        "lng_max": 93.4,
        "radius_km": 170.0,
    },
    {
        "name": "Sikkim",
        "boundary_type": "state",
        "country": "India",
        "state": None,
        "lat_min": 27.1,
        "lat_max": 28.1,
        "lng_min": 88.0,
        "lng_max": 88.9,
        "radius_km": 80.0,
    },
    # ── Pakistan Provinces & Territories ────────────────────────────────────────
    {
        "name": "Punjab",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 27.7,
        "lat_max": 33.0,
        "lng_min": 69.3,
        "lng_max": 75.4,
        "radius_km": 450.0,
    },
    {
        "name": "Sindh",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 23.5,
        "lat_max": 28.5,
        "lng_min": 66.7,
        "lng_max": 71.1,
        "radius_km": 420.0,
    },
    {
        "name": "Khyber Pakhtunkhwa",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 31.1,
        "lat_max": 36.9,
        "lng_min": 69.2,
        "lng_max": 74.1,
        "radius_km": 380.0,
    },
    {
        "name": "Balochistan",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 24.8,
        "lat_max": 32.1,
        "lng_min": 60.9,
        "lng_max": 70.3,
        "radius_km": 700.0,
    },
    {
        "name": "Gilgit-Baltistan",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 34.6,
        "lat_max": 37.1,
        "lng_min": 72.0,
        "lng_max": 77.8,
        "radius_km": 350.0,
    },
    {
        "name": "Azad Kashmir",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 33.0,
        "lat_max": 35.1,
        "lng_min": 73.1,
        "lng_max": 75.1,
        "radius_km": 180.0,
    },
    {
        "name": "Islamabad Capital Territory",
        "boundary_type": "state",
        "country": "Pakistan",
        "state": None,
        "lat_min": 33.6,
        "lat_max": 33.8,
        "lng_min": 72.8,
        "lng_max": 73.3,
        "radius_km": 30.0,
    },
    # ── UAE Cities ───────────────────────────────────────────────────────────────
    {
        "name": "Dubai",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 24.8,
        "lat_max": 25.4,
        "lng_min": 54.9,
        "lng_max": 55.6,
        "radius_km": 40.0,
    },
    {
        "name": "Abu Dhabi",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 24.3,
        "lat_max": 24.6,
        "lng_min": 54.3,
        "lng_max": 54.7,
        "radius_km": 25.0,
    },
    {
        "name": "Sharjah",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 25.2,
        "lat_max": 25.5,
        "lng_min": 55.3,
        "lng_max": 55.6,
        "radius_km": 20.0,
    },
    {
        "name": "Ajman",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 25.38,
        "lat_max": 25.43,
        "lng_min": 55.42,
        "lng_max": 55.48,
        "radius_km": 5.0,
    },
    {
        "name": "Ras Al Khaimah",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 25.75,
        "lat_max": 25.85,
        "lng_min": 55.9,
        "lng_max": 56.0,
        "radius_km": 10.0,
    },
    {
        "name": "Fujairah",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 25.1,
        "lat_max": 25.2,
        "lng_min": 56.3,
        "lng_max": 56.4,
        "radius_km": 10.0,
    },
    {
        "name": "Umm Al Quwain",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 25.54,
        "lat_max": 25.58,
        "lng_min": 55.52,
        "lng_max": 55.58,
        "radius_km": 5.0,
    },
    {
        "name": "Al Ain",
        "boundary_type": "city",
        "country": "UAE",
        "state": None,
        "lat_min": 24.1,
        "lat_max": 24.3,
        "lng_min": 55.6,
        "lng_max": 55.9,
        "radius_km": 20.0,
    },
    # ── India Cities ─────────────────────────────────────────────────────────────
    {
        "name": "Mumbai",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 18.9,
        "lat_max": 19.3,
        "lng_min": 72.8,
        "lng_max": 73.0,
        "radius_km": 30.0,
    },
    {
        "name": "Delhi",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 28.4,
        "lat_max": 28.9,
        "lng_min": 76.8,
        "lng_max": 77.4,
        "radius_km": 35.0,
    },
    {
        "name": "Bangalore",
        "boundary_type": "city",
        "country": "India",
        "state": "Karnataka",
        "lat_min": 12.8,
        "lat_max": 13.1,
        "lng_min": 77.5,
        "lng_max": 77.8,
        "radius_km": 25.0,
    },
    {
        "name": "Hyderabad",
        "boundary_type": "city",
        "country": "India",
        "state": "Andhra Pradesh",
        "lat_min": 17.3,
        "lat_max": 17.6,
        "lng_min": 78.3,
        "lng_max": 78.6,
        "radius_km": 25.0,
    },
    {
        "name": "Chennai",
        "boundary_type": "city",
        "country": "India",
        "state": "Tamil Nadu",
        "lat_min": 12.9,
        "lat_max": 13.2,
        "lng_min": 80.1,
        "lng_max": 80.3,
        "radius_km": 20.0,
    },
    {
        "name": "Kolkata",
        "boundary_type": "city",
        "country": "India",
        "state": "West Bengal",
        "lat_min": 22.4,
        "lat_max": 22.7,
        "lng_min": 88.3,
        "lng_max": 88.5,
        "radius_km": 20.0,
    },
    {
        "name": "Pune",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 18.4,
        "lat_max": 18.7,
        "lng_min": 73.7,
        "lng_max": 74.0,
        "radius_km": 25.0,
    },
    {
        "name": "Ahmedabad",
        "boundary_type": "city",
        "country": "India",
        "state": "Gujarat",
        "lat_min": 22.9,
        "lat_max": 23.2,
        "lng_min": 72.5,
        "lng_max": 72.7,
        "radius_km": 20.0,
    },
    {
        "name": "Jaipur",
        "boundary_type": "city",
        "country": "India",
        "state": "Rajasthan",
        "lat_min": 26.8,
        "lat_max": 27.0,
        "lng_min": 75.7,
        "lng_max": 75.9,
        "radius_km": 20.0,
    },
    {
        "name": "Lucknow",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 26.7,
        "lat_max": 26.9,
        "lng_min": 80.8,
        "lng_max": 81.0,
        "radius_km": 15.0,
    },
    {
        "name": "Kanpur",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 26.4,
        "lat_max": 26.5,
        "lng_min": 80.3,
        "lng_max": 80.4,
        "radius_km": 15.0,
    },
    {
        "name": "Nagpur",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 21.0,
        "lat_max": 21.3,
        "lng_min": 79.0,
        "lng_max": 79.2,
        "radius_km": 20.0,
    },
    {
        "name": "Indore",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 22.6,
        "lat_max": 22.8,
        "lng_min": 75.8,
        "lng_max": 76.0,
        "radius_km": 15.0,
    },
    {
        "name": "Thane",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 19.1,
        "lat_max": 19.3,
        "lng_min": 72.9,
        "lng_max": 73.1,
        "radius_km": 15.0,
    },
    {
        "name": "Bhopal",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 23.1,
        "lat_max": 23.4,
        "lng_min": 77.3,
        "lng_max": 77.5,
        "radius_km": 20.0,
    },
    {
        "name": "Visakhapatnam",
        "boundary_type": "city",
        "country": "India",
        "state": "Andhra Pradesh",
        "lat_min": 17.6,
        "lat_max": 17.8,
        "lng_min": 83.1,
        "lng_max": 83.4,
        "radius_km": 20.0,
    },
    {
        "name": "Patna",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 25.5,
        "lat_max": 25.7,
        "lng_min": 85.0,
        "lng_max": 85.2,
        "radius_km": 15.0,
    },
    {
        "name": "Vadodara",
        "boundary_type": "city",
        "country": "India",
        "state": "Gujarat",
        "lat_min": 22.2,
        "lat_max": 22.4,
        "lng_min": 73.1,
        "lng_max": 73.3,
        "radius_km": 15.0,
    },
    {
        "name": "Ghaziabad",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 28.6,
        "lat_max": 28.7,
        "lng_min": 77.4,
        "lng_max": 77.5,
        "radius_km": 10.0,
    },
    {
        "name": "Ludhiana",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 30.8,
        "lat_max": 31.0,
        "lng_min": 75.8,
        "lng_max": 76.0,
        "radius_km": 15.0,
    },
    {
        "name": "Agra",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 27.1,
        "lat_max": 27.3,
        "lng_min": 77.9,
        "lng_max": 78.1,
        "radius_km": 15.0,
    },
    {
        "name": "Nashik",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 19.9,
        "lat_max": 20.1,
        "lng_min": 73.7,
        "lng_max": 73.9,
        "radius_km": 15.0,
    },
    {
        "name": "Faridabad",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 28.3,
        "lat_max": 28.5,
        "lng_min": 77.2,
        "lng_max": 77.4,
        "radius_km": 15.0,
    },
    {
        "name": "Meerut",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 28.9,
        "lat_max": 29.1,
        "lng_min": 77.6,
        "lng_max": 77.8,
        "radius_km": 15.0,
    },
    {
        "name": "Rajkot",
        "boundary_type": "city",
        "country": "India",
        "state": "Gujarat",
        "lat_min": 22.2,
        "lat_max": 22.4,
        "lng_min": 70.7,
        "lng_max": 70.9,
        "radius_km": 15.0,
    },
    {
        "name": "Varanasi",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 25.2,
        "lat_max": 25.4,
        "lng_min": 82.9,
        "lng_max": 83.1,
        "radius_km": 15.0,
    },
    {
        "name": "Srinagar",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 34.0,
        "lat_max": 34.2,
        "lng_min": 74.7,
        "lng_max": 74.9,
        "radius_km": 15.0,
    },
    {
        "name": "Aurangabad",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 19.8,
        "lat_max": 19.9,
        "lng_min": 75.2,
        "lng_max": 75.4,
        "radius_km": 10.0,
    },
    {
        "name": "Dhanbad",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 23.7,
        "lat_max": 23.9,
        "lng_min": 86.3,
        "lng_max": 86.5,
        "radius_km": 15.0,
    },
    {
        "name": "Amritsar",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 31.5,
        "lat_max": 31.7,
        "lng_min": 74.8,
        "lng_max": 75.0,
        "radius_km": 15.0,
    },
    {
        "name": "Allahabad",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 25.4,
        "lat_max": 25.5,
        "lng_min": 81.8,
        "lng_max": 81.9,
        "radius_km": 10.0,
    },
    {
        "name": "Ranchi",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 23.3,
        "lat_max": 23.4,
        "lng_min": 85.2,
        "lng_max": 85.4,
        "radius_km": 10.0,
    },
    {
        "name": "Howrah",
        "boundary_type": "city",
        "country": "India",
        "state": "West Bengal",
        "lat_min": 22.5,
        "lat_max": 22.7,
        "lng_min": 88.2,
        "lng_max": 88.4,
        "radius_km": 15.0,
    },
    {
        "name": "Coimbatore",
        "boundary_type": "city",
        "country": "India",
        "state": "Tamil Nadu",
        "lat_min": 10.9,
        "lat_max": 11.1,
        "lng_min": 76.9,
        "lng_max": 77.1,
        "radius_km": 15.0,
    },
    {
        "name": "Jabalpur",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 23.1,
        "lat_max": 23.2,
        "lng_min": 79.9,
        "lng_max": 80.0,
        "radius_km": 10.0,
    },
    {
        "name": "Gwalior",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 26.2,
        "lat_max": 26.3,
        "lng_min": 78.1,
        "lng_max": 78.2,
        "radius_km": 10.0,
    },
    {
        "name": "Vijayawada",
        "boundary_type": "city",
        "country": "India",
        "state": "Andhra Pradesh",
        "lat_min": 16.4,
        "lat_max": 16.6,
        "lng_min": 80.5,
        "lng_max": 80.7,
        "radius_km": 15.0,
    },
    {
        "name": "Jodhpur",
        "boundary_type": "city",
        "country": "India",
        "state": "Rajasthan",
        "lat_min": 26.2,
        "lat_max": 26.4,
        "lng_min": 73.0,
        "lng_max": 73.1,
        "radius_km": 15.0,
    },
    {
        "name": "Madurai",
        "boundary_type": "city",
        "country": "India",
        "state": "Tamil Nadu",
        "lat_min": 9.9,
        "lat_max": 10.0,
        "lng_min": 78.0,
        "lng_max": 78.2,
        "radius_km": 10.0,
    },
    {
        "name": "Raipur",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 21.2,
        "lat_max": 21.3,
        "lng_min": 81.5,
        "lng_max": 81.7,
        "radius_km": 10.0,
    },
    {
        "name": "Kota",
        "boundary_type": "city",
        "country": "India",
        "state": "Rajasthan",
        "lat_min": 25.1,
        "lat_max": 25.3,
        "lng_min": 75.8,
        "lng_max": 76.0,
        "radius_km": 15.0,
    },
    {
        "name": "Chandigarh",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 30.6,
        "lat_max": 30.8,
        "lng_min": 76.7,
        "lng_max": 76.9,
        "radius_km": 15.0,
    },
    {
        "name": "Guwahati",
        "boundary_type": "city",
        "country": "India",
        "state": None,
        "lat_min": 26.1,
        "lat_max": 26.3,
        "lng_min": 91.7,
        "lng_max": 91.9,
        "radius_km": 15.0,
    },
    {
        "name": "Solapur",
        "boundary_type": "city",
        "country": "India",
        "state": "Maharashtra",
        "lat_min": 17.6,
        "lat_max": 17.7,
        "lng_min": 75.9,
        "lng_max": 76.0,
        "radius_km": 10.0,
    },
    {
        "name": "Hubli",
        "boundary_type": "city",
        "country": "India",
        "state": "Karnataka",
        "lat_min": 15.3,
        "lat_max": 15.4,
        "lng_min": 75.1,
        "lng_max": 75.2,
        "radius_km": 10.0,
    },
    {
        "name": "Mysore",
        "boundary_type": "city",
        "country": "India",
        "state": "Karnataka",
        "lat_min": 12.2,
        "lat_max": 12.4,
        "lng_min": 76.6,
        "lng_max": 76.7,
        "radius_km": 15.0,
    },
    {
        "name": "Tiruchirappalli",
        "boundary_type": "city",
        "country": "India",
        "state": "Tamil Nadu",
        "lat_min": 10.7,
        "lat_max": 10.9,
        "lng_min": 78.6,
        "lng_max": 78.8,
        "radius_km": 15.0,
    },
    {
        "name": "Bareilly",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 28.3,
        "lat_max": 28.4,
        "lng_min": 79.4,
        "lng_max": 79.5,
        "radius_km": 10.0,
    },
    {
        "name": "Aligarh",
        "boundary_type": "city",
        "country": "India",
        "state": "Uttar Pradesh",
        "lat_min": 27.8,
        "lat_max": 28.0,
        "lng_min": 78.0,
        "lng_max": 78.2,
        "radius_km": 15.0,
    },
    {
        "name": "Tiruppur",
        "boundary_type": "city",
        "country": "India",
        "state": "Tamil Nadu",
        "lat_min": 11.0,
        "lat_max": 11.2,
        "lng_min": 77.3,
        "lng_max": 77.4,
        "radius_km": 10.0,
    },
    # ── Pakistan Cities (Top 50 by population) ───────────────────────────────────
    {
        "name": "Karachi",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 24.7,
        "lat_max": 25.1,
        "lng_min": 66.8,
        "lng_max": 67.2,
        "radius_km": 50.0,
    },
    {
        "name": "Lahore",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.4,
        "lat_max": 31.7,
        "lng_min": 74.2,
        "lng_max": 74.5,
        "radius_km": 35.0,
    },
    {
        "name": "Faisalabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.3,
        "lat_max": 31.6,
        "lng_min": 72.9,
        "lng_max": 73.2,
        "radius_km": 25.0,
    },
    {
        "name": "Rawalpindi",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 33.5,
        "lat_max": 33.7,
        "lng_min": 73.0,
        "lng_max": 73.2,
        "radius_km": 20.0,
    },
    {
        "name": "Gujranwala",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.1,
        "lat_max": 32.3,
        "lng_min": 74.1,
        "lng_max": 74.3,
        "radius_km": 20.0,
    },
    {
        "name": "Peshawar",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 33.9,
        "lat_max": 34.1,
        "lng_min": 71.4,
        "lng_max": 71.6,
        "radius_km": 20.0,
    },
    {
        "name": "Multan",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.0,
        "lat_max": 30.3,
        "lng_min": 71.4,
        "lng_max": 71.7,
        "radius_km": 20.0,
    },
    {
        "name": "Hyderabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 25.3,
        "lat_max": 25.5,
        "lng_min": 68.3,
        "lng_max": 68.5,
        "radius_km": 15.0,
    },
    {
        "name": "Islamabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Islamabad Capital Territory",
        "lat_min": 33.6,
        "lat_max": 33.8,
        "lng_min": 73.0,
        "lng_max": 73.2,
        "radius_km": 20.0,
    },
    {
        "name": "Quetta",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Balochistan",
        "lat_min": 30.1,
        "lat_max": 30.3,
        "lng_min": 66.9,
        "lng_max": 67.1,
        "radius_km": 15.0,
    },
    {
        "name": "Bahawalpur",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 29.3,
        "lat_max": 29.5,
        "lng_min": 71.6,
        "lng_max": 71.8,
        "radius_km": 15.0,
    },
    {
        "name": "Sargodha",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.0,
        "lat_max": 32.2,
        "lng_min": 72.6,
        "lng_max": 72.8,
        "radius_km": 15.0,
    },
    {
        "name": "Sialkot",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.4,
        "lat_max": 32.6,
        "lng_min": 74.4,
        "lng_max": 74.6,
        "radius_km": 15.0,
    },
    {
        "name": "Sukkur",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 27.6,
        "lat_max": 27.8,
        "lng_min": 68.8,
        "lng_max": 69.0,
        "radius_km": 15.0,
    },
    {
        "name": "Larkana",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 27.5,
        "lat_max": 27.7,
        "lng_min": 68.1,
        "lng_max": 68.3,
        "radius_km": 10.0,
    },
    {
        "name": "Sheikhupura",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.6,
        "lat_max": 31.8,
        "lng_min": 73.9,
        "lng_max": 74.1,
        "radius_km": 10.0,
    },
    {
        "name": "Jhang",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.2,
        "lat_max": 31.4,
        "lng_min": 72.2,
        "lng_max": 72.4,
        "radius_km": 10.0,
    },
    {
        "name": "Rahim Yar Khan",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 28.3,
        "lat_max": 28.5,
        "lng_min": 70.2,
        "lng_max": 70.4,
        "radius_km": 10.0,
    },
    {
        "name": "Gujrat",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.5,
        "lat_max": 32.7,
        "lng_min": 74.0,
        "lng_max": 74.2,
        "radius_km": 10.0,
    },
    {
        "name": "Mardan",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 34.1,
        "lat_max": 34.3,
        "lng_min": 71.9,
        "lng_max": 72.1,
        "radius_km": 10.0,
    },
    {
        "name": "Kasur",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.0,
        "lat_max": 31.2,
        "lng_min": 74.4,
        "lng_max": 74.6,
        "radius_km": 10.0,
    },
    {
        "name": "Dera Ghazi Khan",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 29.9,
        "lat_max": 30.2,
        "lng_min": 70.5,
        "lng_max": 70.7,
        "radius_km": 15.0,
    },
    {
        "name": "Nawabshah",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 26.1,
        "lat_max": 26.3,
        "lng_min": 68.3,
        "lng_max": 68.5,
        "radius_km": 10.0,
    },
    {
        "name": "Mingora",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 34.7,
        "lat_max": 34.9,
        "lng_min": 72.3,
        "lng_max": 72.5,
        "radius_km": 10.0,
    },
    {
        "name": "Chiniot",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 31.6,
        "lat_max": 31.8,
        "lng_min": 72.9,
        "lng_max": 73.1,
        "radius_km": 10.0,
    },
    {
        "name": "Sahiwal",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.6,
        "lat_max": 30.8,
        "lng_min": 73.0,
        "lng_max": 73.2,
        "radius_km": 10.0,
    },
    {
        "name": "Okara",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.7,
        "lat_max": 30.9,
        "lng_min": 73.3,
        "lng_max": 73.5,
        "radius_km": 10.0,
    },
    {
        "name": "Mirpur Khas",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 25.4,
        "lat_max": 25.6,
        "lng_min": 68.9,
        "lng_max": 69.1,
        "radius_km": 10.0,
    },
    {
        "name": "Abbottabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 34.1,
        "lat_max": 34.2,
        "lng_min": 73.1,
        "lng_max": 73.3,
        "radius_km": 10.0,
    },
    {
        "name": "Khanewal",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.2,
        "lat_max": 30.4,
        "lng_min": 71.9,
        "lng_max": 72.1,
        "radius_km": 10.0,
    },
    {
        "name": "Hafizabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.0,
        "lat_max": 32.2,
        "lng_min": 73.6,
        "lng_max": 73.8,
        "radius_km": 10.0,
    },
    {
        "name": "Kohat",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 33.5,
        "lat_max": 33.7,
        "lng_min": 71.4,
        "lng_max": 71.6,
        "radius_km": 10.0,
    },
    {
        "name": "Jacobabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 28.2,
        "lat_max": 28.4,
        "lng_min": 68.4,
        "lng_max": 68.6,
        "radius_km": 10.0,
    },
    {
        "name": "Muzaffargarh",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.0,
        "lat_max": 30.2,
        "lng_min": 71.1,
        "lng_max": 71.3,
        "radius_km": 10.0,
    },
    {
        "name": "Khanpur",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 28.6,
        "lat_max": 28.8,
        "lng_min": 70.6,
        "lng_max": 70.8,
        "radius_km": 10.0,
    },
    {
        "name": "Ghotki",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 27.9,
        "lat_max": 28.1,
        "lng_min": 69.2,
        "lng_max": 69.4,
        "radius_km": 10.0,
    },
    {
        "name": "Burewala",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 30.1,
        "lat_max": 30.3,
        "lng_min": 72.6,
        "lng_max": 72.8,
        "radius_km": 10.0,
    },
    {
        "name": "Jhelum",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.8,
        "lat_max": 33.0,
        "lng_min": 73.6,
        "lng_max": 73.8,
        "radius_km": 10.0,
    },
    {
        "name": "Khairpur",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 27.4,
        "lat_max": 27.6,
        "lng_min": 68.6,
        "lng_max": 68.8,
        "radius_km": 10.0,
    },
    {
        "name": "Sadiqabad",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 28.2,
        "lat_max": 28.4,
        "lng_min": 70.0,
        "lng_max": 70.2,
        "radius_km": 10.0,
    },
    {
        "name": "Wah Cantt",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 33.7,
        "lat_max": 33.9,
        "lng_min": 72.6,
        "lng_max": 72.8,
        "radius_km": 10.0,
    },
    {
        "name": "Dera Ismail Khan",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 31.7,
        "lat_max": 31.9,
        "lng_min": 70.8,
        "lng_max": 71.0,
        "radius_km": 10.0,
    },
    {
        "name": "Chakwal",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.8,
        "lat_max": 33.0,
        "lng_min": 72.8,
        "lng_max": 73.0,
        "radius_km": 10.0,
    },
    {
        "name": "Mianwali",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 32.5,
        "lat_max": 32.7,
        "lng_min": 71.4,
        "lng_max": 71.6,
        "radius_km": 10.0,
    },
    {
        "name": "Lodhran",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 29.4,
        "lat_max": 29.6,
        "lng_min": 71.5,
        "lng_max": 71.7,
        "radius_km": 10.0,
    },
    {
        "name": "Attock",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Punjab",
        "lat_min": 33.7,
        "lat_max": 33.9,
        "lng_min": 72.3,
        "lng_max": 72.5,
        "radius_km": 10.0,
    },
    {
        "name": "Tando Adam",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Sindh",
        "lat_min": 25.7,
        "lat_max": 25.9,
        "lng_min": 68.6,
        "lng_max": 68.8,
        "radius_km": 10.0,
    },
    {
        "name": "Khuzdar",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Balochistan",
        "lat_min": 27.7,
        "lat_max": 27.9,
        "lng_min": 66.5,
        "lng_max": 66.7,
        "radius_km": 10.0,
    },
    {
        "name": "Turbat",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Balochistan",
        "lat_min": 25.9,
        "lat_max": 26.1,
        "lng_min": 62.9,
        "lng_max": 63.1,
        "radius_km": 10.0,
    },
    {
        "name": "Nowshera",
        "boundary_type": "city",
        "country": "Pakistan",
        "state": "Khyber Pakhtunkhwa",
        "lat_min": 33.9,
        "lat_max": 34.1,
        "lng_min": 71.9,
        "lng_max": 72.1,
        "radius_km": 10.0,
    },
]


def seed_geo_boundaries(session: Session):
    """Seed geographic boundaries — deletes existing data and re-inserts fresh."""
    from sqlalchemy import delete as _delete

    # Delete child rows first (FK constraint: geoboundarybox → geoboundary)
    session.exec(_delete(GeoBoundaryBox))
    session.exec(_delete(GeoBoundary))
    session.commit()

    for boundary_data in GEO_BOUNDARIES:
        session.add(GeoBoundary(**boundary_data))
    session.commit()
    logger.info("Seeded %d geographic boundaries (fresh)", len(GEO_BOUNDARIES))


# ── Multi-box country borders ─────────────────────────────────────────────────
#
# Tighter sub-boxes per country reduce wasted search area and avoid
# cross-border contamination.  ~15-20 boxes per large country, 4-6 for smaller.
# Keys match GeoBoundary.name values.
#
COUNTRY_BOXES: dict[str, list[dict]] = {
    # ── India (26 boxes) ─────────────────────────────────────────────────────
    # A single India rectangle covers Pakistan, Bangladesh, Nepal, Sri Lanka.
    # 26 tighter boxes trace the actual inhabited landmass.
    # Changes vs previous 25-box set:
    #   - northwest_punjab_haryana: lng_min 73.8→74.0 (avoids Pakistan Punjab border zone)
    #   - jammu_kashmir: split into jammu + kashmir_valley (avoids PoK and Aksai Chin)
    #   - west_gujarat: lat_max 24.5→22.8 (reduces redundancy with new gujarat_northwest box)
    #   - gujarat_northwest: new box (lat 22.5-24.0, lng 68.5-71.5) for Kutch/Bhuj
    # Changes vs previous 18-box set:
    #   - northwest_rajasthan: lng_min 69.5→70.7 (India-Pak border ~70.5°E in Rajasthan)
    #   - north_bihar_east_jharkhand: lng_max 88.0→87.5 (Bangladesh border starts ~87.5°E)
    #   - northeast_west_bengal: lng_max 89.5→88.5 (Bangladesh western border ~88.0°E)
    #   - northeast_assam_meghalaya: single huge box (89.5-96.0) split into 5 boxes
    "India": [
        # Trimmed lng_min 73.8→74.0 — avoids marginal Pakistan Punjab border zone (~74°E)
        {
            "label": "northwest_punjab_haryana",
            "lat_min": 28.5,
            "lat_max": 32.5,
            "lng_min": 74.0,
            "lng_max": 77.5,
        },
        # Rajasthan split: east of the Aravalli Range is populated (Jaipur, Ajmer,
        # Udaipur, Jodhpur, Bikaner, Sri Ganganagar, Churu, Nagaur).
        {
            "label": "rajasthan_east",
            "lat_min": 24.0,
            "lat_max": 30.0,
            "lng_min": 73.0,
            "lng_max": 76.5,
        },
        # Western Thar Desert: sparse but has Jaisalmer (26.91°N, 70.92°E),
        # Barmer (25.75°N, 71.38°E). Excludes extreme SW desert (lat < 25.5).
        {
            "label": "rajasthan_west_desert",
            "lat_min": 25.5,
            "lat_max": 28.5,
            "lng_min": 70.7,
            "lng_max": 73.0,
        },
        # Trimmed lat_max 31.5→30.8 — above 30.8°N is uninhabited high Himalaya.
        # Keeps Joshimath (30.55°N), Chamoli, all hill towns.
        {
            "label": "north_uttarakhand_up_west",
            "lat_min": 27.5,
            "lat_max": 30.8,
            "lng_min": 77.5,
            "lng_max": 81.5,
        },
        {
            "label": "north_up_east_bihar_west",
            "lat_min": 25.0,
            "lat_max": 28.5,
            "lng_min": 78.5,
            "lng_max": 84.5,
        },
        # Trimmed lng_max 88.0 → 87.5 — Bangladesh border starts ~87.5°E at these latitudes.
        {
            "label": "north_bihar_east_jharkhand",
            "lat_min": 22.5,
            "lat_max": 27.5,
            "lng_min": 83.5,
            "lng_max": 87.5,
        },
        # Trimmed lng_max 89.5 → 88.5 — Bangladesh western border is ~88.0°E;
        # 89.5 was bleeding well into Bangladesh.
        {
            "label": "northeast_west_bengal",
            "lat_min": 21.5,
            "lat_max": 27.5,
            "lng_min": 86.0,
            "lng_max": 88.5,
        },
        # ── Previous single "northeast_assam_meghalaya" box (89.5-96.0) ──────
        # That one box covered all NE India in one sweep and bled into Myanmar
        # (border ~95.5-96.5°E) and Bangladesh (lng 89.5 at low latitudes).
        # Split into 5 tighter boxes:
        # Assam valley and Meghalaya plateau
        {
            "label": "northeast_assam",
            "lat_min": 25.0,
            "lat_max": 27.5,
            "lng_min": 89.5,
            "lng_max": 93.5,
        },
        {
            "label": "northeast_meghalaya",
            "lat_min": 24.5,
            "lat_max": 26.5,
            "lng_min": 89.5,
            "lng_max": 92.5,
        },
        # Tripura and Mizoram (narrow strip between Bangladesh and Myanmar)
        {
            "label": "northeast_tripura_mizoram",
            "lat_min": 22.5,
            "lat_max": 24.5,
            "lng_min": 91.5,
            "lng_max": 93.5,
        },
        # Manipur and Nagaland — capped at 95.5°E (Myanmar border starts ~95.5-96°E)
        {
            "label": "northeast_manipur_nagaland",
            "lat_min": 23.5,
            "lat_max": 26.5,
            "lng_min": 93.5,
            "lng_max": 95.5,
        },
        # Arunachal Pradesh — trimmed lat_max 29.5→28.5 (above is uninhabited
        # high-altitude terrain) and lng_max 97.0→96.5 (extreme east is dense
        # forest). Keeps Itanagar (27.09°N), Pasighat (28.07°N), Tezu (27.92°N).
        {
            "label": "northeast_arunachal",
            "lat_min": 26.5,
            "lat_max": 28.5,
            "lng_min": 91.5,
            "lng_max": 96.5,
        },
        # ── Jammu & Kashmir — split into 2 tighter boxes ──────────────────────
        # Previous single box (lat 33.0-36.5, lng 73.8-78.5) covered Pakistan-occupied
        # Kashmir and Chinese Aksai Chin territory (east of ~79°E above lat 34°N).
        # Jammu division — below Line of Control
        {
            "label": "jammu",
            "lat_min": 32.5,
            "lat_max": 34.5,
            "lng_min": 74.0,
            "lng_max": 76.5,
        },
        # Kashmir valley — stays west of Aksai Chin
        {
            "label": "kashmir_valley",
            "lat_min": 33.5,
            "lat_max": 35.0,
            "lng_min": 73.8,
            "lng_max": 75.5,
        },
        {
            "label": "central_mp_west",
            "lat_min": 21.5,
            "lat_max": 25.5,
            "lng_min": 74.0,
            "lng_max": 79.0,
        },
        {
            "label": "central_mp_east_chhattisgarh",
            "lat_min": 19.5,
            "lat_max": 23.5,
            "lng_min": 79.0,
            "lng_max": 84.5,
        },
        {
            "label": "central_odisha",
            "lat_min": 17.8,
            "lat_max": 22.5,
            "lng_min": 82.5,
            "lng_max": 87.5,
        },
        # Trimmed lat_max 24.5→22.8 — upper Gujarat now covered by new gujarat_northwest box
        {
            "label": "west_gujarat",
            "lat_min": 20.0,
            "lat_max": 22.8,
            "lng_min": 68.0,
            "lng_max": 74.5,
        },
        # Gujarat northwest (Kutch/Bhuj) — trimmed lat_max 24.0→23.5 to exclude
        # the Great Rann of Kutch salt marsh (uninhabited above ~23.3°N).
        # Bhuj at 23.25°N, 69.67°E is the main settlement.
        {
            "label": "gujarat_northwest",
            "lat_min": 22.5,
            "lat_max": 23.5,
            "lng_min": 68.5,
            "lng_max": 71.5,
        },
        {
            "label": "west_maharashtra_north",
            "lat_min": 19.5,
            "lat_max": 22.5,
            "lng_min": 73.5,
            "lng_max": 80.5,
        },
        {
            "label": "west_maharashtra_south_goa",
            "lat_min": 15.0,
            "lat_max": 19.5,
            "lng_min": 73.0,
            "lng_max": 78.0,
        },
        {
            "label": "south_karnataka",
            "lat_min": 11.5,
            "lat_max": 15.5,
            "lng_min": 74.5,
            "lng_max": 78.5,
        },
        {
            "label": "south_andhra_telangana",
            "lat_min": 13.5,
            "lat_max": 19.5,
            "lng_min": 77.5,
            "lng_max": 84.5,
        },
        {
            "label": "south_tamilnadu",
            "lat_min": 8.0,
            "lat_max": 13.5,
            "lng_min": 76.5,
            "lng_max": 80.5,
        },
        {
            "label": "south_kerala",
            "lat_min": 8.0,
            "lat_max": 12.5,
            "lng_min": 74.8,
            "lng_max": 77.5,
        },
        {
            "label": "south_ap_coast",
            "lat_min": 13.5,
            "lat_max": 17.5,
            "lng_min": 79.5,
            "lng_max": 82.5,
        },
    ],
    # ── Pakistan (6 boxes) ───────────────────────────────────────────────────
    "Pakistan": [
        {"label": "punjab", "lat_min": 29.0, "lat_max": 33.5, "lng_min": 69.5, "lng_max": 75.5},
        {"label": "sindh", "lat_min": 23.5, "lat_max": 28.5, "lng_min": 66.5, "lng_max": 71.5},
        {"label": "kpk", "lat_min": 31.5, "lat_max": 35.5, "lng_min": 69.5, "lng_max": 73.5},
        {
            "label": "balochistan",
            "lat_min": 25.0,
            "lat_max": 31.5,
            "lng_min": 60.9,
            "lng_max": 67.5,
        },
        {"label": "ajk", "lat_min": 33.0, "lat_max": 35.0, "lng_min": 73.0, "lng_max": 75.5},
        {
            "label": "gilgit_baltistan",
            "lat_min": 35.0,
            "lat_max": 37.1,
            "lng_min": 72.5,
            "lng_max": 77.8,
        },
    ],
    # ── USA (16 boxes — continental US only) ─────────────────────────────────
    "USA": [
        {
            "label": "pacific_northwest",
            "lat_min": 45.5,
            "lat_max": 49.0,
            "lng_min": -124.5,
            "lng_max": -116.5,
        },
        {
            "label": "california_north",
            "lat_min": 37.0,
            "lat_max": 42.0,
            "lng_min": -124.5,
            "lng_max": -119.0,
        },
        {
            "label": "california_south",
            "lat_min": 32.5,
            "lat_max": 37.0,
            "lng_min": -120.5,
            "lng_max": -114.0,
        },
        {
            "label": "mountain_northwest",
            "lat_min": 42.0,
            "lat_max": 49.0,
            "lng_min": -117.5,
            "lng_max": -110.5,
        },
        {
            "label": "mountain_southwest",
            "lat_min": 31.5,
            "lat_max": 42.5,
            "lng_min": -114.5,
            "lng_max": -107.5,
        },
        {
            "label": "great_plains_north",
            "lat_min": 40.0,
            "lat_max": 49.0,
            "lng_min": -110.5,
            "lng_max": -97.5,
        },
        {
            "label": "great_plains_south",
            "lat_min": 26.0,
            "lat_max": 40.0,
            "lng_min": -107.5,
            "lng_max": -97.5,
        },
        {"label": "texas", "lat_min": 25.5, "lat_max": 36.5, "lng_min": -106.5, "lng_max": -93.5},
        {
            "label": "midwest_north",
            "lat_min": 41.0,
            "lat_max": 49.0,
            "lng_min": -97.5,
            "lng_max": -84.0,
        },
        {
            "label": "midwest_south",
            "lat_min": 35.0,
            "lat_max": 41.5,
            "lng_min": -97.5,
            "lng_max": -87.5,
        },
        {
            "label": "south_central",
            "lat_min": 29.0,
            "lat_max": 35.5,
            "lng_min": -94.5,
            "lng_max": -84.5,
        },
        {
            "label": "southeast",
            "lat_min": 24.5,
            "lat_max": 35.5,
            "lng_min": -87.5,
            "lng_max": -80.0,
        },
        {
            "label": "great_lakes_east",
            "lat_min": 41.5,
            "lat_max": 47.5,
            "lng_min": -84.5,
            "lng_max": -76.5,
        },
        {
            "label": "northeast",
            "lat_min": 39.5,
            "lat_max": 47.5,
            "lng_min": -80.0,
            "lng_max": -66.5,
        },
        {
            "label": "mid_atlantic",
            "lat_min": 36.5,
            "lat_max": 41.5,
            "lng_min": -81.0,
            "lng_max": -73.5,
        },
        {"label": "florida", "lat_min": 24.5, "lat_max": 31.0, "lng_min": -87.5, "lng_max": -80.0},
    ],
    # ── UAE (9 boxes) ────────────────────────────────────────────────────────
    # Optimized to exclude the Empty Quarter desert and Abu Dhabi interior
    # desert (abu_dhabi_desert box deleted — 100% uninhabited, was 6,200 cells).
    # abu_dhabi_liwa replaced by 3 targeted boxes around actual settlements.
    # Total cells: ~8,400 per type (down from ~20,800 — 59% reduction).
    "UAE": [
        # Western Abu Dhabi coast: Sila, Ruwais (24.12°N), Mirfa (24.09°N)
        {
            "label": "western_coast",
            "lat_min": 23.9,
            "lat_max": 24.3,
            "lng_min": 51.5,
            "lng_max": 53.7,
        },
        # Ghayathi (23.84°N) and Madinat Zayed (23.66°N) cluster
        {
            "label": "ghayathi_madinat_zayed",
            "lat_min": 23.5,
            "lat_max": 24.0,
            "lng_min": 52.5,
            "lng_max": 54.0,
        },
        # Liwa oasis arc — tight strip around the ~50 villages (pop ~20,000)
        {
            "label": "liwa_oasis",
            "lat_min": 23.0,
            "lat_max": 23.3,
            "lng_min": 53.2,
            "lng_max": 54.3,
        },
        # Abu Dhabi metro: city, Saadiyat, Yas, Khalifa City, MBZ City, Shahama
        {
            "label": "abu_dhabi_metro",
            "lat_min": 24.25,
            "lat_max": 24.70,
            "lng_min": 54.20,
            "lng_max": 55.00,
        },
        # Al Ain city proper — Oman's Buraimi immediately east at ~55.8°E
        {
            "label": "al_ain",
            "lat_min": 24.05,
            "lat_max": 24.35,
            "lng_min": 55.50,
            "lng_max": 55.80,
        },
        # Dubai emirate: Jebel Ali to Deira
        {
            "label": "dubai",
            "lat_min": 24.85,
            "lat_max": 25.4,
            "lng_min": 54.9,
            "lng_max": 55.55,
        },
        # Sharjah, Ajman, Umm Al Quwain coastal strip
        {
            "label": "sharjah_ajman_uaq",
            "lat_min": 25.2,
            "lat_max": 25.65,
            "lng_min": 55.28,
            "lng_max": 55.65,
        },
        # Ras Al Khaimah — capped at lat 25.9°N below Musandam (Oman exclave)
        {
            "label": "rak_main",
            "lat_min": 25.55,
            "lat_max": 25.9,
            "lng_min": 55.85,
            "lng_max": 56.05,
        },
        # Fujairah coast: Kalba (25.00°N) to Dibba (25.59°N), narrow Gulf of Oman strip.
        # Merged fujairah_south + rak_east_coast + fujairah_dibba into one strip —
        # capped at lat 25.55°N and lng 56.35°E to avoid Oman.
        {
            "label": "fujairah_coast",
            "lat_min": 24.95,
            "lat_max": 25.55,
            "lng_min": 56.0,
            "lng_max": 56.35,
        },
    ],
}


def seed_geo_boundary_boxes(session: Session) -> None:
    """Seed GeoBoundaryBox rows from COUNTRY_BOXES — deletes existing data and re-inserts."""
    from sqlalchemy import delete as _delete

    session.exec(_delete(GeoBoundaryBox))
    session.commit()

    for country_name, box_defs in COUNTRY_BOXES.items():
        boundary = session.exec(select(GeoBoundary).where(GeoBoundary.name == country_name)).first()
        if not boundary:
            logger.warning("seed_geo_boundary_boxes: %r not found — skipping", country_name)
            continue

        for box_def in box_defs:
            session.add(
                GeoBoundaryBox(
                    boundary_id=boundary.id,
                    lat_min=box_def["lat_min"],
                    lat_max=box_def["lat_max"],
                    lng_min=box_def["lng_min"],
                    lng_max=box_def["lng_max"],
                    label=box_def.get("label"),
                )
            )
        session.commit()
        logger.info("Seeded %d boxes for %r", len(box_defs), country_name)


if __name__ == "__main__":
    from app.db.session import engine

    with Session(engine) as session:
        seed_geo_boundaries(session)
        seed_geo_boundary_boxes(session)
